### ISSUE TITLE
Support for Openfl +8?

### ISSUE THREAD

**Issue by xmorpher** [Tw1ddle/samcodes-admob#12]
Do you plan to support OpenFL 8 for this amazing library? ^_^

**Comment by Tw1ddle** [comment]
That's the plan, should have that done in the next week or so 👍

**Comment by xmorpher** [comment]
Great!!!!!! 
:-D

**Comment by Tw1ddle** [comment]
Hi, I've had a go at updating this, haven't had chance to test it out yet. Could you try the current version in the repo latest OpenFL, and let me know if it's working OK for you and your games?

**Comment by xmorpher** [comment]
Ok, i'll try it and let you know, thanks!

**Comment by xmorpher** [comment]
I'm getting this error: 

AndroidManifest.xml
20       28:65 :AAPT: no resource found that matches the given name (at 'value' with value '@ integer/google_play_services_version').

And the value is present in the project.xml as always

**Comment by Tw1ddle** [comment]
Thanks, annoyingly I don't see that error when testing my demo app (https://github.com/Tw1ddle/samcodes-ads-demo). This is using the latest samcodes-admob submodule in the demo repo, and with the samcodes-admob flag set in Project.xml...

I have Google Play Services version 49 installed through SDK manager, and Android minimum SDK version set to 14 in Project.xml. What versions of these are you using? Could you also try the demo project above and tell me if you get an error?

Another issue to be aware of - your path to your Android export folder has to be very short (like C:\my_project), otherwise the gradle build process hits the 240 character Windows path length limit when working with some of the Google Play Services resources, and fails. Not sure what to do about that.

**Comment by xmorpher** [comment]
I have the latest lime/openfl/android sdk available versions... , i'll test the demo app and let you know...

**Comment by xmorpher** [comment]
When i compile the demo it fails if you uncomment the line:
`<!-- <set name="admobads" if="android" /> -->`
and i get the same error...

`AndroidManifest.xml
20 28:65 :AAPT: no resource found that matches the given name (at 'value' with value '@ integer/google_play_services_version').
`
(it doesn't  fail with that line commented but is needed for android build)

it works for you with the line uncommented?

**Comment by Tw1ddle** [comment]
Yes, I'm compiling with that uncommented and it builds for me. Could you confirm that your SDK Tools versions are the same as mine? Here are mine:

<img width="514" alt="screenshot_418" src="https://user-images.githubusercontent.com/1332318/40329028-263dee8a-5d40-11e8-8c3b-8ff0f8aacfdc.png">

**Comment by xmorpher** [comment]
We tried with the same configuration and got the same error, 
so maybe is something in our part, but we have the latest lime/openfl/haxe versions from haxelib
and the latest android sdk settings as well... 
What java version are you using in your android setup?

**Comment by GregorHaag** [comment]
@xmorpher could you fix it? Because i got the same error now.

**Comment by xmorpher** [comment]
@GregorHaag  We solved using the Android NDK R15 instead of the latest version

**Comment by GregorHaag** [comment]
Solved
Using the git version directly does work!
(using Openfl 8.4.1, Lime7.0.0, hxcpp 4.0.4, ndkr15c)

@Tw1ddle thereis a bug with "haxelib install samcodes-admob", it installs not the most recent git version, but an older one (with the wrong JNI import) and apparently some other bugs

**Comment by Tw1ddle** [comment]
I'm no longer using this haxelib, so am unlikely to push a working version to haxelib itself. I think the OpenFL 8 support was working at the time I wrote it (on the git version) though!
