### ISSUE TITLE
Stopped working since the openfl-gpg lib got deprecated

### ISSUE THREAD

**Issue by xmorpher** [Tw1ddle/samcodes-admob#3]
Hi, Thanks for your extensions, they're very good
I just wanted to let you know that samcodes-admob
is not working since the library: openfl-gpg 1.43 is deprecated 
(and now is called extension-googleplaygames but it has the same functionality)
i hope you can update it to work on this version...
Regards!

**Comment by Tw1ddle** [comment]
Thanks, will have a look soon :+1:

**Comment by Tw1ddle** [comment]
I just pushed up version 1.0.5 with the dependency fixed. I didn't have time to test properly because the demo graphics are broken on my phone atm, but it can't hurt.

I'll be able to take a proper look soon and make sure everything works as it should, if you have a chance in the meantime let me know if it's okay for you. Thanks :+1:

**Comment by xmorpher** [comment]
i will check it and get back to you, thanks!

**Comment by xmorpher** [comment]
it seems to work fine, thanks!

**Comment by Tw1ddle** [comment]
Great!
