### ISSUE TITLE
build failed  , openfl 4

### ISSUE THREAD

**Issue by FlashTang** [Tw1ddle/samcodes-admob#8]
Hi Tw1ddle

build failed  , openfl 4

/usr/local/lib/haxe/lib/samcodes-admob/1,0,9/extension/admob/AdMob.hx:75: characters 16-24 : Class<openfl.Lib> has no field load

how can I fix it ？

thanks

**Comment by Tw1ddle** [comment]
Hi @FlashTang thanks for reporting the issue. I haven't properly tested the haxelib for OpenFL 4, so that is probably where the issue lies. I have been waiting for OpenFL 4.x support to be added to HaxeFlixel, since that is what my test app uses: https://github.com/Tw1ddle/samcodes-ads-demo

When OpenFL 4.x support is added to HaxeFlixel, I will certainly update this haxelib. For the time being, you could also try: https://github.com/openfl/extension-admob which I believe is well supported on the latest OpenFL versions.

**Comment by Tw1ddle** [comment]
HaxeFlixel has been updated with OpenFL 8 support, so updating this haxelib and demo at last. Will be fixed in the next haxelib release 👍
